"""Assemble the final YOLO dataset under datasets/processed/.

Consumes the merged dataset plus merged/splits.json and produces the
exact layout configs/dataset.yaml declares:

    processed/
    ├── images/{train,val,test}/
    ├── labels/{train,val,test}/
    └── data.yaml        (generated; matches configs/dataset.yaml)

The images/, labels/, and data.yaml entries are rebuilt from scratch
on every run; nothing else in processed/ is touched, and the merged
and raw datasets are only read.
"""
import shutil
import sys
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

from ai.object_detection.config import DatasetConfig, load_dataset_config
from ai.object_detection.data_tools.split import SPLIT_NAMES, load_splits
from ai.object_detection.paths import MERGED_DATA_DIR, PROCESSED_DATA_DIR
from ai.shared.utils.logger import get_logger

log = get_logger("data_tools.build")


@dataclass
class BuildResult:
    """Outcome of one processed-dataset build."""

    processed_dir: str
    built_at: str
    images_per_split: dict[str, int] = field(default_factory=dict)
    data_yaml: str = ""

    @property
    def images_total(self) -> int:
        """Number of images across all splits."""
        return sum(self.images_per_split.values())


def build_processed(
    merged_dir: Path = MERGED_DATA_DIR,
    processed_dir: Path = PROCESSED_DATA_DIR,
    dataset_cfg: DatasetConfig | None = None,
) -> BuildResult:
    """Copy merged files into the final YOLO layout and write data.yaml.

    Args:
        merged_dir: Merged dataset with images/, labels/, splits.json.
        processed_dir: Output root declared by configs/dataset.yaml.
        dataset_cfg: Unified dataset config; loaded when omitted.

    Returns:
        Per-split image counts and the generated data.yaml path.

    Raises:
        FileNotFoundError: If the merged dataset or splits.json is
            missing, or a split-assigned file disappeared.
    """
    cfg = dataset_cfg or load_dataset_config()
    assignments = load_splits(merged_dir)
    images_in = merged_dir / "images"
    labels_in = merged_dir / "labels"

    for sub in ("images", "labels"):
        for split in SPLIT_NAMES:
            target = processed_dir / sub / split
            if target.exists():
                shutil.rmtree(target)
            target.mkdir(parents=True)

    result = BuildResult(
        processed_dir=str(processed_dir),
        built_at=datetime.now(timezone.utc).isoformat(timespec="seconds"),
        images_per_split={name: 0 for name in SPLIT_NAMES},
    )
    for name, split in sorted(assignments.items()):
        image = images_in / name
        label = labels_in / f"{Path(name).stem}.txt"
        if not image.is_file() or not label.is_file():
            raise FileNotFoundError(
                f"splits.json references '{name}' but the merged "
                f"image/label pair is missing — re-run merge and split"
            )
        shutil.copy2(image, processed_dir / "images" / split / name)
        shutil.copy2(label, processed_dir / "labels" / split / label.name)
        result.images_per_split[split] += 1

    result.data_yaml = str(_write_data_yaml(processed_dir, cfg))
    return result


def _write_data_yaml(processed_dir: Path, cfg: DatasetConfig) -> Path:
    """Write the Ultralytics data.yaml describing the processed dataset."""
    names = "\n".join(f"  {i}: {name}" for i, name in enumerate(cfg.names))
    content = (
        "# Generated by ai.object_detection.data_tools.build — do not edit.\n"
        "# Regenerate with: python -m ai.object_detection.data_tools.pipeline\n"
        f"path: {processed_dir.resolve().as_posix()}\n"
        f"train: {cfg.train}\n"
        f"val: {cfg.val}\n"
        f"test: {cfg.test}\n"
        f"nc: {cfg.nc}\n"
        f"names:\n{names}\n"
    )
    path = processed_dir / "data.yaml"
    path.write_text(content, encoding="utf-8")
    return path


def main(argv: list[str] | None = None) -> int:
    """CLI entry point: build datasets/processed/ from the merged set."""
    result = build_processed()
    log.info("built %s: %s (total %d images); data.yaml: %s",
             result.processed_dir, result.images_per_split,
             result.images_total, result.data_yaml)
    return 0


if __name__ == "__main__":
    sys.exit(main())
